version: '3.5'

services:

  db-postgres:
    container_name: db-postgres
    image: postgres
    environment:
      POSTGRES_DB: ${DEFAULT_DATABASE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${COMMON_DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./data/db-postgres/:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - net

  php-fpm-8.1:
    container_name: php-fpm-8.1
    build:
      context: ./php-fpm/8.1
      args:
        userName: ${DOCKER_USER_NAME}
        userGroup: ${DOCKER_USER_GROUP}
    environment:
      - PHP_IDE_CONFIG=serverName=php8.1
      - XDEBUG_CONFIG=client_host=172.17.0.1 log_level=0
    volumes:
      - ./server:/var/www/html
      - ./php-fpm/8.1/php.ini:/usr/local/etc/php/php.ini
    networks:
      - net
    depends_on:
      - db-postgres

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8000-8100:8000-8100'
    volumes:
      - ./server:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/php8.1.conf:/etc/nginx/php8.1.conf
    depends_on:
      - php-fpm-8.1
      - db-postgres
    networks:
      - net

networks:
  net:
    driver: bridge
    external: false