###
// получение цен бумаг
GET http://iss.moex.com/iss/statistics/engines/stock/currentprices.json?tradingsession=1&iss.meta
Content-Type: application/json

###
GET https://iss.moex.com/iss/engines/stock/markets/shares/boards/TQBR/securities.json?iss.meta=off&iss.only=marketdata&marketdata.columns=SECID,LAST