###
// создать пользователя
POST http://localhost:8000/user/create
Content-Type: application/json

> {%
    client.global.set("apiKey", response.body.apiKey);
%}

###
// получить список портфелей пользователя
GET http://localhost:8000/api/briefcase
Content-Type: application/json
Authorization: Bearer {{apiKey}}

###
// создать пустой портфель пользователя
POST http://localhost:8000/api/briefcase
Content-Type: application/json
Authorization: Bearer {{apiKey}}

###
// Добавление акции в портфель
POST http://localhost:8000/api/briefcase/promotion/add
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "briefcaseId": 7,
  "ticker": "BSPBP",
  "quantity": 100
}

###
// Удаление акции из портфеля
POST http://localhost:8000/api/briefcase/promotion/delete
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "briefcaseId": 7,
  "ticker": "AFLT",
  "quantity": 5
}

###
// Просмотр стоимости портфеля
POST http://localhost:8000/api/briefcase/total_cost
Content-Type: application/json
Authorization: Bearer {{apiKey}}

{
  "briefcaseId": 7
}

###
